"""

===Adam Mangoroban - amangor1@umbc.edu - Data Privacy 2026 spring semester ===
===Portions of this code was generated by Claude with supervision and edits===


===Car Sticker Analyzer===
Uses Claude Haiku 4.5 to detect and categorize decals/stickers on the back of cars.
Outputs a structured JSON file with sticker details per image.


Usage:
    python sticker_analyzer.py <image1> <image2> ... [--output results.json]

Examples:
    python sticker_analyzer.py car1.jpg car2.png
    python sticker_analyzer.py ./images/*.jpg --output stickers.json
    python sticker_analyzer.py car.jpg --output stickers.json --append
"""

import glob
import anthropic
import base64
import json
import argparse
import sys
import os
from pathlib import Path


MODEL = "claude-haiku-4-5-20251001"

LABEL_CODES = """
| Label     | Code | Description |
|-----------|------|-------------|
| Political | POL  | Political names, party logos, election slogans, policy stance, protest signs, political statements |
| Religious | REL  | Religious symbols, religious figures, church/faith-related symbols |
| Family    | FAM  | Children, student, pet, wedding stickers, flowers, dates |
| Education | EDU  | College logos, honor roll, school sports, fraternity/sorority logos |
| Advert    | ADV  | Brand logos, business names, product ads, dealership stickers |
| Location  | LOC  | State names, landmarks, street signs, regional identifiers |
| Other     | OTH  | Hobbies, sports teams, veteran, police, humor, anything that doesn't fit above |
| Unknown   | UNK  | Too blurry or unidentifiable |
"""

SYSTEM_PROMPT = f"""You are an expert at analyzing vehicle decals and stickers from photographs.
Your job is to identify every sticker or decal visible on the back of a car, then classify each one.

Use ONLY these category codes:
{LABEL_CODES}

Rules:
- Identify every sticker/decal you can see, no matter how small
- If the image does not show the back of a car, return an empty stickers array
- XY location should be expressed as a percentage of image width/height (0-100), representing the CENTER of the sticker
  Format: {{"x": 42, "y": 78}}  (x = left->right %, y = top->bottom %)
- Be short but specific in your reasoning, describe what you see that led to the classification
- Respond ONLY with a valid JSON object, no markdown, no explanation outside the JSON

Response format:
{{
  "stickers": [
    {{
      "id": 1,
      "location": {{"x": <0-100>, "y": <0-100>}},
      "label": "<Full Label Name>",
      "code": "<3-letter code>",
      "reasoning": "<What you see and why you chose this category>"
    }}
  ]
}}"""


def load_image(image_path: str) -> tuple[str, str]:
    """Load an image file and return (base64_data, media_type)."""
    path = Path(image_path)
    suffix = path.suffix.lower()

    media_type_map = {
        ".jpg":  "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png":  "image/png",
        ".gif":  "image/gif",
        ".webp": "image/webp",
    }

    media_type = media_type_map.get(suffix)
    if not media_type:
        raise ValueError(f"Unsupported image format: {suffix}. Use JPG, PNG, GIF, or WEBP.")

    with open(path, "rb") as f:
        data = base64.standard_b64encode(f.read()).decode("utf-8")

    return data, media_type


def analyze_image(client: anthropic.Anthropic, image_path: str) -> dict:
    """Send one image to Claude Haiku and return the parsed sticker analysis."""
    print(f"  Analyzing: {image_path}")

    image_data, media_type = load_image(image_path)

    message = client.messages.create(
        model=MODEL,
        max_tokens=1000,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": image_data,
                        },
                    },
                    {
                        "type": "text",
                        "text": "Please identify and classify all stickers/decals on the back of this car.",
                    },
                ],
            }
        ],
    )

    raw = message.content[0].text.strip()

    # Strip accidental markdown fences
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    parsed = json.loads(raw)
    return parsed.get("stickers", [])


def build_entry(image_path: str, stickers: list) -> dict:
    """Build the output entry for a single image."""
    entry = {"image": Path(image_path).name, "stickers": {}}

    for i, sticker in enumerate(stickers, start=1):
        key = f"sticker_{i}"
        entry["stickers"][key] = {
            "location": sticker.get("location", {}),
            "label":    sticker.get("label", "Unknown"),
            "code":     sticker.get("code", "UNK"),
            "reasoning": sticker.get("reasoning", ""),
        }

    entry["sticker_count"] = len(stickers)
    return entry


def load_existing_results(output_path: str) -> dict:
    """Load existing JSON results file, or return empty dict."""
    if os.path.exists(output_path):
        with open(output_path, "r") as f:
            return json.load(f)
    return {"results": []}


def save_results(results: dict, output_path: str) -> None:
    """Save results to a JSON file."""
    with open(output_path, "w") as f:
        json.dump(results, f, indent=2)



def main():
    parser = argparse.ArgumentParser(
        description="Analyze car stickers using Claude Haiku 4.5"
    )
    parser.add_argument(
        "images",
        nargs="+",
        help="One or more image file paths to analyze"
    )
    parser.add_argument(
        "--output", "-o",
        default="sticker_results.json",
        help="Output JSON file path (default: sticker_results.json)"
    )
    parser.add_argument(
        "--append", "-a",
        action="store_true",
        help="Append to existing output file instead of overwriting"
    )
    parser.add_argument(
        "--api-key",
        default=None,
        help="Anthropic API key (or set ANTHROPIC_API_KEY environment variable)"
    )
    args = parser.parse_args()

    valid_images = []
    for pattern in args.images:
        matches = glob.glob(pattern)
        if matches:
            valid_images.extend(matches)
        elif os.path.isfile(pattern):
            valid_images.append(pattern)
        else:
            print(f"  WARNING: File not found, skipping: {img}", file=sys.stderr)

    if not valid_images:
        print("ERROR: No valid image files provided.", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=args.api_key)  # falls back to ANTHROPIC_API_KEY env var

    results = load_existing_results(args.output) if args.append else {"results": []}

    print(f"\nProcessing {len(valid_images)} image(s)...\n")
    success_count = 0

    for image_path in valid_images:
        try:
            stickers = analyze_image(client, image_path)
            entry = build_entry(image_path, stickers)
            results["results"].append(entry)

            sticker_count = entry["sticker_count"]
            codes = [s["code"] for s in entry["stickers"].values()]
            print(f"Found {sticker_count} sticker(s): {', '.join(codes) if codes else 'none'}\n")
            success_count += 1

        except json.JSONDecodeError as e:
            print(f"Failed to parse Claude response for {image_path}: {e}", file=sys.stderr)
        except Exception as e:
            print(f"Error processing {image_path}: {e}", file=sys.stderr)

    save_results(results, args.output)
    print(f"Done. {success_count}/{len(valid_images)} images processed.")
    print(f"Results saved to: {args.output}\n")


if __name__ == "__main__":
    main()